// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/common/recommand/card.vue')['default']
    Container: typeof import('./src/components/common/recommand/container.vue')['default']
    CustomPopover: typeof import('./src/components/common/custom-popover.vue')['default']
    CustomSwipe: typeof import('./src/components/common/custom-swipe.vue')['default']
    Navbar: typeof import('./src/components/common/navbar.vue')['default']
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCard: typeof import('@nutui/nutui-taro')['Card']
    NutCategory: typeof import('@nutui/nutui-taro')['Category']
    NutCategoryPane: typeof import('@nutui/nutui-taro')['CategoryPane']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCellGroup: typeof import('@nutui/nutui-taro')['CellGroup']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutEllipsis: typeof import('@nutui/nutui-taro')['Ellipsis']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutGrid: typeof import('@nutui/nutui-taro')['Grid']
    NutGridItem: typeof import('@nutui/nutui-taro')['GridItem']
    NutIcon: typeof import('@nutui/nutui-taro')['Icon']
    NutInputNumber: typeof import('@nutui/nutui-taro')['InputNumber']
    NutMenu: typeof import('@nutui/nutui-taro')['Menu']
    NutMenuItem: typeof import('@nutui/nutui-taro')['MenuItem']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutPrice: typeof import('@nutui/nutui-taro')['Price']
    NutSearchbar: typeof import('@nutui/nutui-taro')['Searchbar']
    NutSku: typeof import('@nutui/nutui-taro')['Sku']
    NutSwipe: typeof import('@nutui/nutui-taro')['Swipe']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTag: typeof import('@nutui/nutui-taro')['Tag']
    NutToast: typeof import('@nutui/nutui-taro')['Toast']
    OperateBar: typeof import('./src/components/common/operate-bar.vue')['default']
    RecommandCol: typeof import('./src/components/common/recommand/recommand-col.vue')['default']
    RecommandRow: typeof import('./src/components/common/recommand/recommand-row.vue')['default']
  }
}
